import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello world, Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link className={styles.link} href="/about">Click here to About Me</Link>
        <Link className={styles.link} href="/blogs">Click here to List of Blog Posts</Link>
        <Link className={styles.link} href="/users">Click here to List of DB Users</Link>
      </main>
    </div>
  );
}
